### PR TITLE
Make Universal (and up-to-date)

### PR DESCRIPTION
**Pull request by fgblomqvist**
Found this buildpack the other day and it's really handy!
However, I did have to modify it to work with my setup, which I believe is according to the current standard (the migrate.py script was phased out I think). Let me know if you have any feedback, and feel free to decline it in case I am wrong  about it being a standard setup (using `alembic.ini` and `alembic upgrade head`).

### CODE REVIEW

**Comment by revmischa** [comment]
migrate.py was phased out?
Will need to test this out before merging

**Comment by fgblomqvist** [comment]
Sorry for my late response. I was not able to find any information on migrate.py, which is why I assumed it was phased out.

**Comment by revmischa** [comment]
Migrate.py is described here https://realpython.com/blog/python/flask-by-example-part-2-postgres-sqlalchemy-and-alembic/
For using with flask/sqlalchemy

**Comment by fgblomqvist** [comment]
I wasn't able to find any references to migrate.py on that page? Do you mean _manage.py_? That one was phased out. Nonetheless, that post is from 2014. Manage.py was a suggestion by Flask-Migrate (https://flask-migrate.readthedocs.io/en/latest/) back when Flask-Script was current. Flask-Script was phased out in favor of the new Flask CLI not too long ago. The Flask CLI does not require any extra files (e.g. migrate.py, manage.py) to function.

If you are aiming to just support Flask-Migrate, you should rename the buildpack accordingly (and call `flask db migrate` etc.). If you aim on supporting alembic, then you should call the alembic commands instead (`alembic upgrade head` etc.).

**Comment by revmischa** [comment]
I'll try it out. Sorta waiting on this: https://bitbucket.org/zzzeek/alembic/issues/460/heads-doesnt-run-envpy

**Comment by revmischa** [comment]
By the way you're better off just using a migrate command in a release dyno

**Comment by fgblomqvist** [comment]
Yeah I just read that issue. Was wondering why my imports weren't working, would make my life easier. Hopefully they work eventually. Are you saying import in the migrate files will work if I use the migrate command?

**Comment by revmischa** [comment]
maybe try setting PYTHONPATH, or setting things up in env.py.

**Pull request merged**
